# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings

title: Algoritmit ja Tekoäly Harjoitustyö
email: jeremias.berg@helsinki.fi
description: >- # this means to ignore newlines until "baseurl:"
baseurl: ''
url: 'https://algolabra-hy.github.io'
moodle: 'https://moodle.helsinki.fi/course/view.php?id=66945'
norppa: 'https://norppa.helsinki.fi/targets/83052940/feedback'
github_username: jezberg
repo_url: 'https://github.com/algolabra-hy/algolabra-hy.github.io'
repo_branch: 'master'


# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
